application: ms-dev
version: test-1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webob
  version: latest
- name: jinja2
  version: 2.6

builtins:
- remote_api: on

includes:
- include-python27.yaml

handlers:
- url: .*
  script: examples.app
  login: admin

